/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.extendDirty.basic;

import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import com.landawn.abacus.annotation.Type;

public class AclUser implements ExtendDirtyBasicPNL.AclUserPNL {
    private long id;
    private String gui;
    private String name;
    private String description;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createdTime;
    private List<AclGroup> groupList;

    public AclUser() {
    }

    public AclUser(long id) {
        this();

        setId(id);
    }

    public AclUser(String gui, String name, String description, int status, Timestamp lastUpdateTime, Timestamp createdTime, List<AclGroup> groupList) {
        this();

        setGUI(gui);
        setName(name);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreatedTime(createdTime);
        setGroupList(groupList);
    }

    public AclUser(long id, String gui, String name, String description, int status, Timestamp lastUpdateTime, Timestamp createdTime, List<AclGroup> groupList) {
        this();

        setId(id);
        setGUI(gui);
        setName(name);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreatedTime(createdTime);
        setGroupList(groupList);
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public AclUser setId(long id) {
        this.id = id;

        return this;
    }

    @Type("String")
    public String getGUI() {
        return gui;
    }

    public AclUser setGUI(String gui) {
        this.gui = gui;

        return this;
    }

    @Type("String")
    public String getName() {
        return name;
    }

    public AclUser setName(String name) {
        this.name = name;

        return this;
    }

    @Type("String")
    public String getDescription() {
        return description;
    }

    public AclUser setDescription(String description) {
        this.description = description;

        return this;
    }

    @Type("int")
    public int getStatus() {
        return status;
    }

    public AclUser setStatus(int status) {
        this.status = status;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    public AclUser setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getCreatedTime() {
        return createdTime;
    }

    public AclUser setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;

        return this;
    }

    @Type("List<com.landawn.abacus.entity.extendDirty.basic.AclGroup>")
    public List<AclGroup> getGroupList() {
        return groupList;
    }

    public AclUser setGroupList(List<AclGroup> groupList) {
        this.groupList = groupList;

        return this;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(id);
        h = 31 * h + Objects.hashCode(gui);
        h = 31 * h + Objects.hashCode(name);
        h = 31 * h + Objects.hashCode(description);
        h = 31 * h + Objects.hashCode(status);
        h = 31 * h + Objects.hashCode(lastUpdateTime);
        h = 31 * h + Objects.hashCode(createdTime);
        return 31 * h + Objects.hashCode(groupList);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof AclUser other) {
            return Objects.equals(id, other.id) && Objects.equals(gui, other.gui) && Objects.equals(name, other.name)
                    && Objects.equals(description, other.description) && Objects.equals(status, other.status)
                    && Objects.equals(lastUpdateTime, other.lastUpdateTime) && Objects.equals(createdTime, other.createdTime)
                    && Objects.equals(groupList, other.groupList);
        }

        return false;
    }

    @Override
    public String toString() {
        return "{id=" + Objects.toString(id) + ", gui=" + Objects.toString(gui) + ", name=" + Objects.toString(name) + ", description="
                + Objects.toString(description) + ", status=" + Objects.toString(status) + ", lastUpdateTime=" + Objects.toString(lastUpdateTime)
                + ", createdTime=" + Objects.toString(createdTime) + ", groupList=" + Objects.toString(groupList) + "}";
    }
}
