/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.extendDirty.basic;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public interface ExtendDirtyBasicCNL {
    String _DN = "extendDirtyBasic".intern();

    public interface AccountCNL {
        String __ = "account".intern();

        String ID = (__ + ".id").intern();

        String GUI = (__ + ".gui").intern();

        String EMAIL_ADDRESS = (__ + ".email_address").intern();

        String FIRST_NAME = (__ + ".first_name").intern();

        String MIDDLE_NAME = (__ + ".middle_name").intern();

        String LAST_NAME = (__ + ".last_name").intern();

        String BIRTH_DATE = (__ + ".birth_date").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections
                .unmodifiableList(Arrays.asList(ID, GUI, EMAIL_ADDRESS, FIRST_NAME, MIDDLE_NAME, LAST_NAME, BIRTH_DATE, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("Account.id".intern(), "Account.gui".intern(), "Account.emailAddress".intern(),
                "Account.firstName".intern(), "Account.middleName".intern(), "Account.lastName".intern(), "Account.birthDate".intern(),
                "Account.status".intern(), "Account.lastUpdateTime".intern(), "Account.createdTime".intern()));
    }

    public interface AccountContactCNL {
        String __ = "account_contact".intern();

        String ID = (__ + ".id").intern();

        String ACCOUNT_ID = (__ + ".account_id").intern();

        String MOBILE = (__ + ".mobile").intern();

        String TELEPHONE = (__ + ".telephone").intern();

        String EMAIL = (__ + ".email").intern();

        String ADDRESS = (__ + ".address").intern();

        String ADDRESS_2 = (__ + ".address_2").intern();

        String CITY = (__ + ".city").intern();

        String STATE = (__ + ".state").intern();

        String COUNTRY = (__ + ".country").intern();

        String ZIP_CODE = (__ + ".zip_code").intern();

        String CATEGORY = (__ + ".category").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, MOBILE, TELEPHONE, EMAIL, ADDRESS, ADDRESS_2, CITY, STATE, COUNTRY,
                ZIP_CODE, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AccountContact.id".intern(), "AccountContact.accountId".intern(),
                "AccountContact.mobile".intern(), "AccountContact.telephone".intern(), "AccountContact.email".intern(), "AccountContact.address".intern(),
                "AccountContact.address2".intern(), "AccountContact.city".intern(), "AccountContact.state".intern(), "AccountContact.country".intern(),
                "AccountContact.zipCode".intern(), "AccountContact.category".intern(), "AccountContact.description".intern(), "AccountContact.status".intern(),
                "AccountContact.lastUpdateTime".intern(), "AccountContact.createdTime".intern()));
    }

    public interface AccountDeviceCNL {
        String __ = "account_device".intern();

        String ID = (__ + ".id").intern();

        String ACCOUNT_ID = (__ + ".account_id").intern();

        String NAME = (__ + ".name").intern();

        String UDID = (__ + ".udid").intern();

        String PLATFORM = (__ + ".platform").intern();

        String MODEL = (__ + ".model").intern();

        String MANUFACTURER = (__ + ".manufacturer").intern();

        String PRODUCE_TIME = (__ + ".produce_time").intern();

        String CATEGORY = (__ + ".category").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER, PRODUCE_TIME, CATEGORY,
                DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections
                .unmodifiableList(Arrays.asList("AccountDevice.id".intern(), "AccountDevice.accountId".intern(), "AccountDevice.name".intern(),
                        "AccountDevice.UDID".intern(), "AccountDevice.platform".intern(), "AccountDevice.model".intern(), "AccountDevice.manufacturer".intern(),
                        "AccountDevice.produceTime".intern(), "AccountDevice.category".intern(), "AccountDevice.description".intern(),
                        "AccountDevice.status".intern(), "AccountDevice.lastUpdateTime".intern(), "AccountDevice.createdTime".intern()));
    }

    public interface AclGroupCNL {
        String __ = "acl_group".intern();

        String ID = (__ + ".id").intern();

        String GUI = (__ + ".gui").intern();

        String NAME = (__ + ".name").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AclGroup.id".intern(), "AclGroup.gui".intern(), "AclGroup.name".intern(),
                "AclGroup.description".intern(), "AclGroup.status".intern(), "AclGroup.lastUpdateTime".intern(), "AclGroup.createdTime".intern()));
    }

    public interface AclTargetCNL {
        String __ = "acl_target".intern();

        String ID = (__ + ".id").intern();

        String GUI = (__ + ".gui").intern();

        String NAME = (__ + ".name").intern();

        String CATEGORY = (__ + ".category").intern();

        String SUB_CATEGORY = (__ + ".sub_category").intern();

        String TYPE = (__ + ".type").intern();

        String SUB_TYPE = (__ + ".sub_type").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections
                .unmodifiableList(Arrays.asList(ID, GUI, NAME, CATEGORY, SUB_CATEGORY, TYPE, SUB_TYPE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AclTarget.id".intern(), "AclTarget.gui".intern(), "AclTarget.name".intern(),
                "AclTarget.category".intern(), "AclTarget.subCategory".intern(), "AclTarget.type".intern(), "AclTarget.subType".intern(),
                "AclTarget.description".intern(), "AclTarget.status".intern(), "AclTarget.lastUpdateTime".intern(), "AclTarget.createdTime".intern()));
    }

    public interface AclUgTargetRelationshipCNL {
        String __ = "acl_ug_target_relationship".intern();

        String ID = (__ + ".id").intern();

        String UG_GUI = (__ + ".ug_gui").intern();

        String TARGET_GUI = (__ + ".target_gui").intern();

        String PRIVILEGE = (__ + ".privilege").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, UG_GUI, TARGET_GUI, PRIVILEGE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AclUgTargetRelationship.id".intern(), "AclUgTargetRelationship.ugGui".intern(),
                "AclUgTargetRelationship.targetGui".intern(), "AclUgTargetRelationship.privilege".intern(), "AclUgTargetRelationship.description".intern(),
                "AclUgTargetRelationship.status".intern(), "AclUgTargetRelationship.lastUpdateTime".intern(), "AclUgTargetRelationship.createdTime".intern()));
    }

    public interface AclUserCNL {
        String __ = "acl_user".intern();

        String ID = (__ + ".id").intern();

        String GUI = (__ + ".gui").intern();

        String NAME = (__ + ".name").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AclUser.id".intern(), "AclUser.gui".intern(), "AclUser.name".intern(),
                "AclUser.description".intern(), "AclUser.status".intern(), "AclUser.lastUpdateTime".intern(), "AclUser.createdTime".intern()));
    }

    public interface AclUserGroupRelationshipCNL {
        String __ = "acl_user_group_relationship".intern();

        String ID = (__ + ".id").intern();

        String USER_GUI = (__ + ".user_gui").intern();

        String GROUP_GUI = (__ + ".group_gui").intern();

        String DESCRIPTION = (__ + ".description").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, USER_GUI, GROUP_GUI, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AclUserGroupRelationship.id".intern(), "AclUserGroupRelationship.userGUI".intern(),
                "AclUserGroupRelationship.groupGUI".intern(), "AclUserGroupRelationship.description".intern(), "AclUserGroupRelationship.status".intern(),
                "AclUserGroupRelationship.lastUpdateTime".intern(), "AclUserGroupRelationship.createdTime".intern()));
    }

    public interface DataTypeCNL {
        String __ = "data_type".intern();

        String BYTETYPE = (__ + ".bytetype").intern();

        String CHARTYPE = (__ + ".chartype").intern();

        String BOOLEANTYPE = (__ + ".booleantype").intern();

        String SHORTTYPE = (__ + ".shorttype").intern();

        String INTTYPE = (__ + ".inttype").intern();

        String LONGTYPE = (__ + ".longtype").intern();

        String FLOATTYPE = (__ + ".floattype").intern();

        String DOUBLETYPE = (__ + ".doubletype").intern();

        String BIG_INTEGER_TYPE = (__ + ".bigIntegerType").intern();

        String BIGDECIMALTYPE = (__ + ".bigdecimaltype").intern();

        String STRINGTYPE = (__ + ".stringtype").intern();

        String BYTEARRAYTYPE = (__ + ".bytearraytype").intern();

        String CHARACTERSTREAMTYPE = (__ + ".characterstreamtype").intern();

        String BINARYSTREAMTYPE = (__ + ".binarystreamtype").intern();

        String CLOBTYPE = (__ + ".clobtype").intern();

        String BLOBTYPE = (__ + ".blobtype").intern();

        String DATETYPE = (__ + ".datetype").intern();

        String TIMETYPE = (__ + ".timetype").intern();

        String TIMESTAMPTYPE = (__ + ".timestamptype").intern();

        String LONG_DATE_TYPE = (__ + ".longDateType").intern();

        String LONG_TIME_TYPE = (__ + ".longTimeType").intern();

        String LONG_TIMESTAMP_TYPE = (__ + ".longTimestampType").intern();

        String ENUM_TYPE = (__ + ".enumType").intern();

        String STRINGARRAYLISTTYPE = (__ + ".stringarraylisttype").intern();

        String BOOLEANLINKEDLISTTYPE = (__ + ".booleanlinkedlisttype").intern();

        String DOUBLEARRAYLISTTYPE = (__ + ".doublearraylisttype").intern();

        String DATEARRAYLISTTYPE = (__ + ".datearraylisttype").intern();

        String TIMESTAMPARRAYLISTTYPE = (__ + ".timestamparraylisttype").intern();

        String BIGDECIMALARRAYLISTTYPE = (__ + ".bigdecimalarraylisttype").intern();

        String STRINGHASHSETTYPE = (__ + ".stringhashsettype").intern();

        String BOOLEANLINKEDHASHSETTYPE = (__ + ".booleanlinkedhashsettype").intern();

        String DATEHASHSETTYPE = (__ + ".datehashsettype").intern();

        String TIMESTAMPHASHSETTYPE = (__ + ".timestamphashsettype").intern();

        String BIGDECIMALHASHSETTYPE = (__ + ".bigdecimalhashsettype").intern();

        String STRINGHASHMAPTYPE = (__ + ".stringhashmaptype").intern();

        String BOOLEANLINKEDHASHMAPTYPE = (__ + ".booleanlinkedhashmaptype").intern();

        String FLOATHASHMAPTYPE = (__ + ".floathashmaptype").intern();

        String DATEHASHMAPTYPE = (__ + ".datehashmaptype").intern();

        String TIMESTAMPHASHMAPTYPE = (__ + ".timestamphashmaptype").intern();

        String BIGDECIMALHASHMAPTYPE = (__ + ".bigdecimalhashmaptype").intern();

        String STRINGVECTORTYPE = (__ + ".stringvectortype").intern();

        String STRINGCONCURRENTHASHMAPTYPE = (__ + ".stringconcurrenthashmaptype").intern();

        String JSON_TYPE = (__ + ".jsonType").intern();

        String XML_TYPE = (__ + ".xmlType").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(BYTETYPE, CHARTYPE, BOOLEANTYPE, SHORTTYPE, INTTYPE, LONGTYPE, FLOATTYPE, DOUBLETYPE,
                BIG_INTEGER_TYPE, BIGDECIMALTYPE, STRINGTYPE, BYTEARRAYTYPE, CHARACTERSTREAMTYPE, BINARYSTREAMTYPE, CLOBTYPE, BLOBTYPE, DATETYPE, TIMETYPE,
                TIMESTAMPTYPE, LONG_DATE_TYPE, LONG_TIME_TYPE, LONG_TIMESTAMP_TYPE, ENUM_TYPE, STRINGARRAYLISTTYPE, BOOLEANLINKEDLISTTYPE, DOUBLEARRAYLISTTYPE,
                DATEARRAYLISTTYPE, TIMESTAMPARRAYLISTTYPE, BIGDECIMALARRAYLISTTYPE, STRINGHASHSETTYPE, BOOLEANLINKEDHASHSETTYPE, DATEHASHSETTYPE,
                TIMESTAMPHASHSETTYPE, BIGDECIMALHASHSETTYPE, STRINGHASHMAPTYPE, BOOLEANLINKEDHASHMAPTYPE, FLOATHASHMAPTYPE, DATEHASHMAPTYPE,
                TIMESTAMPHASHMAPTYPE, BIGDECIMALHASHMAPTYPE, STRINGVECTORTYPE, STRINGCONCURRENTHASHMAPTYPE, JSON_TYPE, XML_TYPE));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("DataType.byteType".intern(), "DataType.charType".intern(),
                "DataType.booleanType".intern(), "DataType.shortType".intern(), "DataType.intType".intern(), "DataType.longType".intern(),
                "DataType.floatType".intern(), "DataType.doubleType".intern(), "DataType.bigIntegerType".intern(), "DataType.bigDecimalType".intern(),
                "DataType.stringType".intern(), "DataType.byteArrayType".intern(), "DataType.characterStreamType".intern(),
                "DataType.binaryStreamType".intern(), "DataType.clobType".intern(), "DataType.blobType".intern(), "DataType.dateType".intern(),
                "DataType.timeType".intern(), "DataType.timestampType".intern(), "DataType.longDateType".intern(), "DataType.longTimeType".intern(),
                "DataType.longTimestampType".intern(), "DataType.enumType".intern(), "DataType.stringArrayListType".intern(),
                "DataType.booleanLinkedListType".intern(), "DataType.doubleListType".intern(), "DataType.dateArrayListType".intern(),
                "DataType.timestampArrayListType".intern(), "DataType.bigDecimalArrayListType".intern(), "DataType.stringHashSetType".intern(),
                "DataType.booleanLinkedHashSetType".intern(), "DataType.dateHashSetType".intern(), "DataType.timestampHashSetType".intern(),
                "DataType.bigDecimalHashSetType".intern(), "DataType.stringHashMapType".intern(), "DataType.booleanLinkedHashMapType".intern(),
                "DataType.floatHashMapType".intern(), "DataType.dateHashMapType".intern(), "DataType.timestampHashMapType".intern(),
                "DataType.bigDecimalHashMapType".intern(), "DataType.stringVectorType".intern(), "DataType.stringConcurrentHashMapType".intern(),
                "DataType.jsonType".intern(), "DataType.xmlType".intern()));
    }

    public interface LoginCNL {
        String __ = "login".intern();

        String ID = (__ + ".id").intern();

        String ACCOUNT_ID = (__ + ".account_id").intern();

        String LOGIN_ID = (__ + ".login_id").intern();

        String LOGIN_PASSWORD = (__ + ".login_password").intern();

        String STATUS = (__ + ".status").intern();

        String LAST_UPDATE_TIME = (__ + ".last_update_time").intern();

        String CREATE_TIME = (__ + ".create_time").intern();

        List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, LOGIN_ID, LOGIN_PASSWORD, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        List<String> _PNL = Collections.unmodifiableList(Arrays.asList("Login.id".intern(), "Login.accountId".intern(), "Login.loginId".intern(),
                "Login.loginPassword".intern(), "Login.status".intern(), "Login.lastUpdateTime".intern(), "Login.createdTime".intern()));
    }

    String ACCOUNT_ID = "account_id".intern();

    String ADDRESS = "address".intern();

    String ADDRESS_2 = "address_2".intern();

    String BIGDECIMALARRAYLISTTYPE = "bigdecimalarraylisttype".intern();

    String BIGDECIMALHASHMAPTYPE = "bigdecimalhashmaptype".intern();

    String BIGDECIMALHASHSETTYPE = "bigdecimalhashsettype".intern();

    String BIGDECIMALTYPE = "bigdecimaltype".intern();

    String BIG_INTEGER_TYPE = "bigIntegerType".intern();

    String BINARYSTREAMTYPE = "binarystreamtype".intern();

    String BIRTH_DATE = "birth_date".intern();

    String BLOBTYPE = "blobtype".intern();

    String BOOLEANLINKEDHASHMAPTYPE = "booleanlinkedhashmaptype".intern();

    String BOOLEANLINKEDHASHSETTYPE = "booleanlinkedhashsettype".intern();

    String BOOLEANLINKEDLISTTYPE = "booleanlinkedlisttype".intern();

    String BOOLEANTYPE = "booleantype".intern();

    String BYTEARRAYTYPE = "bytearraytype".intern();

    String BYTETYPE = "bytetype".intern();

    String CATEGORY = "category".intern();

    String CHARACTERSTREAMTYPE = "characterstreamtype".intern();

    String CHARTYPE = "chartype".intern();

    String CITY = "city".intern();

    String CLOBTYPE = "clobtype".intern();

    String COUNTRY = "country".intern();

    String CREATE_TIME = "create_time".intern();

    String DATEARRAYLISTTYPE = "datearraylisttype".intern();

    String DATEHASHMAPTYPE = "datehashmaptype".intern();

    String DATEHASHSETTYPE = "datehashsettype".intern();

    String DATETYPE = "datetype".intern();

    String DESCRIPTION = "description".intern();

    String DOUBLEARRAYLISTTYPE = "doublearraylisttype".intern();

    String DOUBLETYPE = "doubletype".intern();

    String EMAIL = "email".intern();

    String EMAIL_ADDRESS = "email_address".intern();

    String ENUM_TYPE = "enumType".intern();

    String FIRST_NAME = "first_name".intern();

    String FLOATHASHMAPTYPE = "floathashmaptype".intern();

    String FLOATTYPE = "floattype".intern();

    String GROUP_GUI = "group_gui".intern();

    String GUI = "gui".intern();

    String ID = "id".intern();

    String INTTYPE = "inttype".intern();

    String JSON_TYPE = "jsonType".intern();

    String LAST_NAME = "last_name".intern();

    String LAST_UPDATE_TIME = "last_update_time".intern();

    String LOGIN_ID = "login_id".intern();

    String LOGIN_PASSWORD = "login_password".intern();

    String LONG_DATE_TYPE = "longDateType".intern();

    String LONG_TIMESTAMP_TYPE = "longTimestampType".intern();

    String LONG_TIME_TYPE = "longTimeType".intern();

    String LONGTYPE = "longtype".intern();

    String MANUFACTURER = "manufacturer".intern();

    String MIDDLE_NAME = "middle_name".intern();

    String MOBILE = "mobile".intern();

    String MODEL = "model".intern();

    String NAME = "name".intern();

    String PLATFORM = "platform".intern();

    String PRIVILEGE = "privilege".intern();

    String PRODUCE_TIME = "produce_time".intern();

    String SHORTTYPE = "shorttype".intern();

    String STATE = "state".intern();

    String STATUS = "status".intern();

    String STRINGARRAYLISTTYPE = "stringarraylisttype".intern();

    String STRINGCONCURRENTHASHMAPTYPE = "stringconcurrenthashmaptype".intern();

    String STRINGHASHMAPTYPE = "stringhashmaptype".intern();

    String STRINGHASHSETTYPE = "stringhashsettype".intern();

    String STRINGTYPE = "stringtype".intern();

    String STRINGVECTORTYPE = "stringvectortype".intern();

    String SUB_CATEGORY = "sub_category".intern();

    String SUB_TYPE = "sub_type".intern();

    String TARGET_GUI = "target_gui".intern();

    String TELEPHONE = "telephone".intern();

    String TIMESTAMPARRAYLISTTYPE = "timestamparraylisttype".intern();

    String TIMESTAMPHASHMAPTYPE = "timestamphashmaptype".intern();

    String TIMESTAMPHASHSETTYPE = "timestamphashsettype".intern();

    String TIMESTAMPTYPE = "timestamptype".intern();

    String TIMETYPE = "timetype".intern();

    String TYPE = "type".intern();

    String UDID = "udid".intern();

    String UG_GUI = "ug_gui".intern();

    String USER_GUI = "user_gui".intern();

    String XML_TYPE = "xmlType".intern();

    String ZIP_CODE = "zip_code".intern();
}
