//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.30 at 02:22:28 PM PST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://uk.co.jemos.integration.xml/large-file", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.landawn.abacus.entity;
