package testfixtures.properties;



/**
 * Auto-generated by Abacus.
 */
public class MyProperties extends com.landawn.abacus.util.Properties<java.lang.String, java.lang.Object> {

    public java.lang.String getStrProp2() {
        return (java.lang.String) super.get("strProp2");
    }

    public void setStrProp2(java.lang.String strProp2) {
        super.put("strProp2", strProp2);
    }

    public void removeStrProp2() {
        super.remove("strProp2");
    }

    public MProps4 getMProps4() {
        return (MProps4) super.get("mProps4");
    }

    public void setMProps4(MProps4 mProps4) {
        super.put("mProps4", mProps4);
    }

    public void removeMProps4() {
        super.remove("mProps4");
    }

    public MProps3 getMProps3() {
        return (MProps3) super.get("mProps3");
    }

    public void setMProps3(MProps3 mProps3) {
        super.put("mProps3", mProps3);
    }

    public void removeMProps3() {
        super.remove("mProps3");
    }

    public java.lang.String getIntProp2() {
        return (java.lang.String) super.get("intProp2");
    }

    public void setIntProp2(java.lang.String intProp2) {
        super.put("intProp2", intProp2);
    }

    public void removeIntProp2() {
        super.remove("intProp2");
    }

    public java.lang.String getIntProp1() {
        return (java.lang.String) super.get("intProp1");
    }

    public void setIntProp1(java.lang.String intProp1) {
        super.put("intProp1", intProp1);
    }

    public void removeIntProp1() {
        super.remove("intProp1");
    }

    public java.lang.String getIntProp0() {
        return (java.lang.String) super.get("intProp0");
    }

    public void setIntProp0(java.lang.String intProp0) {
        super.put("intProp0", intProp0);
    }

    public void removeIntProp0() {
        super.remove("intProp0");
    }

    public MProps2 getMProps2() {
        return (MProps2) super.get("mProps2");
    }

    public void setMProps2(MProps2 mProps2) {
        super.put("mProps2", mProps2);
    }

    public void removeMProps2() {
        super.remove("mProps2");
    }

    public MProps1 getMProps1() {
        return (MProps1) super.get("mProps1");
    }

    public void setMProps1(MProps1 mProps1) {
        super.put("mProps1", mProps1);
    }

    public void removeMProps1() {
        super.remove("mProps1");
    }

    public java.lang.String getStrProp() {
        return (java.lang.String) super.get("strProp");
    }

    public void setStrProp(java.lang.String strProp) {
        super.put("strProp", strProp);
    }

    public void removeStrProp() {
        super.remove("strProp");
    }

    @java.lang.Deprecated
    @java.lang.Override
    public MyProperties set(java.lang.String propName, java.lang.Object propValue) {
        return (MyProperties) super.set(propName, propValue);
    }

    @java.lang.Deprecated
    @java.lang.Override
    public java.lang.Object put(java.lang.String propName, java.lang.Object propValue) {
        return super.put(propName, propValue);
    }

    @java.lang.Deprecated
    @java.lang.Override
    public void putAll(java.util.Map<? extends java.lang.String, ? extends java.lang.Object> m) {
        super.putAll(m);
    }

    @java.lang.Deprecated
    @java.lang.Override
    public java.lang.Object remove(java.lang.Object propName) {
        return super.remove(propName);
    }

    public static class MProps4 extends com.landawn.abacus.util.Properties<java.lang.String, java.lang.Object> {

        public java.lang.String getStrProp2() {
            return (java.lang.String) super.get("strProp2");
        }

        public void setStrProp2(java.lang.String strProp2) {
            super.put("strProp2", strProp2);
        }

        public void removeStrProp2() {
            super.remove("strProp2");
        }

        public java.lang.String getIntProp2() {
            return (java.lang.String) super.get("intProp2");
        }

        public void setIntProp2(java.lang.String intProp2) {
            super.put("intProp2", intProp2);
        }

        public void removeIntProp2() {
            super.remove("intProp2");
        }

        public java.lang.String getIntProp1() {
            return (java.lang.String) super.get("intProp1");
        }

        public void setIntProp1(java.lang.String intProp1) {
            super.put("intProp1", intProp1);
        }

        public void removeIntProp1() {
            super.remove("intProp1");
        }

        public java.lang.String getIntProp0() {
            return (java.lang.String) super.get("intProp0");
        }

        public void setIntProp0(java.lang.String intProp0) {
            super.put("intProp0", intProp0);
        }

        public void removeIntProp0() {
            super.remove("intProp0");
        }

        public java.lang.String getStrProp() {
            return (java.lang.String) super.get("strProp");
        }

        public void setStrProp(java.lang.String strProp) {
            super.put("strProp", strProp);
        }

        public void removeStrProp() {
            super.remove("strProp");
        }

        @java.lang.Deprecated
        @java.lang.Override
        public MProps4 set(java.lang.String propName, java.lang.Object propValue) {
            return (MProps4) super.set(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object put(java.lang.String propName, java.lang.Object propValue) {
            return super.put(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public void putAll(java.util.Map<? extends java.lang.String, ? extends java.lang.Object> m) {
            super.putAll(m);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object remove(java.lang.Object propName) {
            return super.remove(propName);
        }
    }

    public static class MProps3 extends com.landawn.abacus.util.Properties<java.lang.String, java.lang.Object> {

        public java.lang.String getStrProp2() {
            return (java.lang.String) super.get("strProp2");
        }

        public void setStrProp2(java.lang.String strProp2) {
            super.put("strProp2", strProp2);
        }

        public void removeStrProp2() {
            super.remove("strProp2");
        }

        public java.lang.String getIntProp2() {
            return (java.lang.String) super.get("intProp2");
        }

        public void setIntProp2(java.lang.String intProp2) {
            super.put("intProp2", intProp2);
        }

        public void removeIntProp2() {
            super.remove("intProp2");
        }

        public java.lang.String getIntProp1() {
            return (java.lang.String) super.get("intProp1");
        }

        public void setIntProp1(java.lang.String intProp1) {
            super.put("intProp1", intProp1);
        }

        public void removeIntProp1() {
            super.remove("intProp1");
        }

        public java.lang.String getIntProp0() {
            return (java.lang.String) super.get("intProp0");
        }

        public void setIntProp0(java.lang.String intProp0) {
            super.put("intProp0", intProp0);
        }

        public void removeIntProp0() {
            super.remove("intProp0");
        }

        public java.lang.String getStrProp() {
            return (java.lang.String) super.get("strProp");
        }

        public void setStrProp(java.lang.String strProp) {
            super.put("strProp", strProp);
        }

        public void removeStrProp() {
            super.remove("strProp");
        }

        @java.lang.Deprecated
        @java.lang.Override
        public MProps3 set(java.lang.String propName, java.lang.Object propValue) {
            return (MProps3) super.set(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object put(java.lang.String propName, java.lang.Object propValue) {
            return super.put(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public void putAll(java.util.Map<? extends java.lang.String, ? extends java.lang.Object> m) {
            super.putAll(m);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object remove(java.lang.Object propName) {
            return super.remove(propName);
        }
    }

    public static class MProps2 extends com.landawn.abacus.util.Properties<java.lang.String, java.lang.Object> {

        public java.lang.String getStrProp2() {
            return (java.lang.String) super.get("strProp2");
        }

        public void setStrProp2(java.lang.String strProp2) {
            super.put("strProp2", strProp2);
        }

        public void removeStrProp2() {
            super.remove("strProp2");
        }

        public java.lang.String getIntProp2() {
            return (java.lang.String) super.get("intProp2");
        }

        public void setIntProp2(java.lang.String intProp2) {
            super.put("intProp2", intProp2);
        }

        public void removeIntProp2() {
            super.remove("intProp2");
        }

        public java.lang.String getIntProp1() {
            return (java.lang.String) super.get("intProp1");
        }

        public void setIntProp1(java.lang.String intProp1) {
            super.put("intProp1", intProp1);
        }

        public void removeIntProp1() {
            super.remove("intProp1");
        }

        public java.lang.String getIntProp0() {
            return (java.lang.String) super.get("intProp0");
        }

        public void setIntProp0(java.lang.String intProp0) {
            super.put("intProp0", intProp0);
        }

        public void removeIntProp0() {
            super.remove("intProp0");
        }

        public java.lang.String getStrProp() {
            return (java.lang.String) super.get("strProp");
        }

        public void setStrProp(java.lang.String strProp) {
            super.put("strProp", strProp);
        }

        public void removeStrProp() {
            super.remove("strProp");
        }

        @java.lang.Deprecated
        @java.lang.Override
        public MProps2 set(java.lang.String propName, java.lang.Object propValue) {
            return (MProps2) super.set(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object put(java.lang.String propName, java.lang.Object propValue) {
            return super.put(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public void putAll(java.util.Map<? extends java.lang.String, ? extends java.lang.Object> m) {
            super.putAll(m);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object remove(java.lang.Object propName) {
            return super.remove(propName);
        }
    }

    public static class MProps1 extends com.landawn.abacus.util.Properties<java.lang.String, java.lang.Object> {

        public java.lang.String getStrProp2() {
            return (java.lang.String) super.get("strProp2");
        }

        public void setStrProp2(java.lang.String strProp2) {
            super.put("strProp2", strProp2);
        }

        public void removeStrProp2() {
            super.remove("strProp2");
        }

        public java.lang.String getIntProp2() {
            return (java.lang.String) super.get("intProp2");
        }

        public void setIntProp2(java.lang.String intProp2) {
            super.put("intProp2", intProp2);
        }

        public void removeIntProp2() {
            super.remove("intProp2");
        }

        public java.lang.String getIntProp1() {
            return (java.lang.String) super.get("intProp1");
        }

        public void setIntProp1(java.lang.String intProp1) {
            super.put("intProp1", intProp1);
        }

        public void removeIntProp1() {
            super.remove("intProp1");
        }

        public java.lang.String getIntProp0() {
            return (java.lang.String) super.get("intProp0");
        }

        public void setIntProp0(java.lang.String intProp0) {
            super.put("intProp0", intProp0);
        }

        public void removeIntProp0() {
            super.remove("intProp0");
        }

        public java.lang.String getStrProp() {
            return (java.lang.String) super.get("strProp");
        }

        public void setStrProp(java.lang.String strProp) {
            super.put("strProp", strProp);
        }

        public void removeStrProp() {
            super.remove("strProp");
        }

        @java.lang.Deprecated
        @java.lang.Override
        public MProps1 set(java.lang.String propName, java.lang.Object propValue) {
            return (MProps1) super.set(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object put(java.lang.String propName, java.lang.Object propValue) {
            return super.put(propName, propValue);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public void putAll(java.util.Map<? extends java.lang.String, ? extends java.lang.Object> m) {
            super.putAll(m);
        }

        @java.lang.Deprecated
        @java.lang.Override
        public java.lang.Object remove(java.lang.Object propName) {
            return super.remove(propName);
        }
    }
}
