/*
 * Copyright (C) 2018 HaiYang Li
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.landawn.abacus.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Marks a field (or names properties at the type level) as a read-only identifier — a primary key
 * that is managed by the database and must not be written by the application. Combines the
 * semantics of {@link Id} and {@link ReadOnly}.
 *
 * <p><b>How the framework consumes it:</b> the reflection layer
 * ({@code com.landawn.abacus.parser.ParserUtil}) flags a property as {@code isMarkedAsReadOnlyId}
 * when ANY of the following is true:</p>
 * <ul>
 *   <li>The property (or its declaring class) carries {@code @ReadOnlyId}.</li>
 *   <li>The property carries both {@code @Id} and {@link ReadOnly}.</li>
 *   <li>The property name appears in the {@link #value()} array of a type-level {@code @ReadOnlyId}.</li>
 * </ul>
 * Such properties are then excluded from generated {@code INSERT} and {@code UPDATE} statements
 * while still appearing in {@code SELECT} results.
 *
 * <p><b>Common scenarios:</b></p>
 * <ul>
 *   <li>Auto-increment primary keys generated by the database.</li>
 *   <li>UUID or sequence-based identifiers assigned by the database side.</li>
 *   <li>Composite keys whose components are all read-only.</li>
 * </ul>
 *
 * <p><b>Per-operation behavior:</b></p>
 * <ul>
 *   <li>{@code INSERT}: the ID property is omitted, letting the database generate the value.</li>
 *   <li>{@code UPDATE}: the ID property is omitted, preventing accidental key changes.</li>
 *   <li>{@code SELECT}: the ID property is included normally for queries and lookups.</li>
 * </ul>
 *
 * <p><b>Usage patterns:</b></p>
 * <ul>
 *   <li>On a field — marks just that single property as a read-only identifier; {@link #value()}
 *       should be left at its default empty array.</li>
 *   <li>On a type — {@link #value()} must list one or more property names that together form the
 *       read-only primary key (typical for composite keys).</li>
 * </ul>
 *
 * <p><b>Usage Examples:</b></p>
 *
 * <p><b>Single read-only ID:</b></p>
 * <pre>{@code
 * @Entity
 * public class User {
 *     @ReadOnlyId
 *     private Long id;            // id is auto-generated by the database.
 *
 *     @Column
 *     private String username;
 * }
 *
 * // Equivalent shorthand using @Id + @ReadOnly:
 * @Entity
 * public class User {
 *     @Id @ReadOnly
 *     private Long id;
 * }
 * }</pre>
 *
 * <p><b>Composite read-only ID at the type level:</b></p>
 * <pre>{@code
 * @Entity
 * @ReadOnlyId({"companyId", "departmentId"})
 * public class Employee {
 *     private Long companyId;     // companyId is set once, never updated.
 *     private Long departmentId;  // departmentId is set once, never updated.
 *     private Long employeeNum;
 * }
 * }</pre>
 *
 * @see Id
 * @see ReadOnly
 */
@Documented
@Target(value = { FIELD, /* METHOD, */ TYPE })
@Retention(RUNTIME)
public @interface ReadOnlyId {

    /**
     * Specifies the property names that form the read-only primary key when {@code @ReadOnlyId}
     * is applied to a type (class).
     *
     * <p>Usage patterns:</p>
     * <ul>
     *   <li>For type-level usage: list one or more property names that comprise the read-only
     *       primary key (the array must be non-empty at the type level).</li>
     *   <li>For field-level usage: this element is typically left at its default (empty array);
     *       the annotated field itself identifies the read-only key.</li>
     * </ul>
     *
     * <p><b>Usage Examples:</b></p>
     * <pre>{@code
     * // Field-level: the annotated field is the read-only primary key.
     * @ReadOnlyId
     * private Long id;
     *
     * // Type-level composite read-only key.
     * @ReadOnlyId({"orderId", "lineNumber"})
     * public class OrderLine { }
     * }</pre>
     *
     * @return the property names forming the read-only identifier at the type level; an empty
     *         array (the default) is the conventional value for field-level usage
     */
    String[] value() default {};

}
