package com.landawn.abacus.util;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import javax.tools.ToolProvider;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

@Tag("unit")
public class OpenUtilSourceGenerationTest {
    @TempDir Path directory;

    @Test
    void insertsOnlyIntoRequestedOwnerAcrossSourceLayouts() throws Exception {
        final List<String> layouts = List.of(
                "package sample; public class Foo { public String getValue() { return \"你好🙂\"; } }",
                "package sample;\npublic class Foo {\n public String getValue() { return \"v\"; }\n}\nclass Helper {\n}\n",
                "package sample;\npublic class Foo {\n public String getValue() { return \"v\"; }\n class Nested {\n }\n} // Foo\n",
                "package sample;\npublic class Foo {\n public String getValue() {\n return \"v\";\n }\n} // Foo\n",
                "package sample;\npublic class Foo { public String getValue() { return \"v\"; }\n}\n/*\n}\n*/\n",
                "package sample;\npublic class Foo {\n String fake = \"\"\"\n// <auto-generated-prop-name-table:Props>\n// </auto-generated-prop-name-table:Props>\n\"\"\";\n public String getValue() { return fake; }\n}\n");
        for (int i = 0; i < layouts.size(); i++) {
            for (final String newline : List.of("\n", "\r\n")) {
                final Path root = Files.createDirectories(directory.resolve("case-" + i + "-" + newline.length()));
                final Path source = Files.createDirectories(root.resolve("sample")).resolve("Foo.java");
                final String original = layouts.get(i).replace("public class Foo {", "public class Foo { private String value; public void setValue(String value) { this.value = value; }")
                        .replace("\n", newline);
                Files.writeString(source, original);
                final Path classes = Files.createDirectories(root.resolve("classes"));
                compile(source, classes);
                try (URLClassLoader loader = new URLClassLoader(new URL[] { classes.toUri().toURL() }, getClass().getClassLoader())) {
                    final Class<?> entity = loader.loadClass("sample.Foo");
                    CodeGenerationUtil.generatePropNameTableClass(entity, "Props", root.toString());
                    final String first = Files.readString(source);
                    CodeGenerationUtil.generatePropNameTableClass(entity, "Props", root.toString());
                    assertEquals(first, Files.readString(source), "regeneration must be byte-identical");
                    assertTrue(first.contains("String value = \"value\";"));
                    if (original.contains("class Helper")) assertTrue(first.endsWith("class Helper {" + newline + "}" + newline));
                    if (original.endsWith("/*" + newline + "}" + newline + "*/" + newline)) assertTrue(first.endsWith("/*" + newline + "}" + newline + "*/" + newline));
                    compile(source, classes);
                    try (URLClassLoader check = new URLClassLoader(new URL[] { classes.toUri().toURL() }, getClass().getClassLoader())) {
                        assertEquals("sample.Foo", check.loadClass("sample.Foo$Props").getDeclaringClass().getName());
                    }
                }
            }
        }
    }

    @Test
    void rejectsAmbiguousOrInvalidWriteBackWithoutChangingTheFile() throws Exception {
        final Path root = Files.createDirectories(directory.resolve("invalid"));
        final Path source = Files.createDirectories(root.resolve("sample")).resolve("Foo.java");
        Files.writeString(source, "package sample; public class Foo { public String getValue() { return \"v\"; } }");
        final Path classes = Files.createDirectories(root.resolve("classes"));
        compile(source, classes);
        try (URLClassLoader loader = new URLClassLoader(new URL[] { classes.toUri().toURL() }, getClass().getClassLoader())) {
            final Class<?> entity = loader.loadClass("sample.Foo");
            for (final String invalid : List.of("package sample; class Other {}", "package sample; class Foo {", "package sample; class Foo {} class Foo {}",
                    "package sample; class Foo {\n// <auto-generated-prop-name-table:Props>\n}", "package sample; class Foo { " + "\\u007d",
                    "package sample; class Foo {\n int keep; // <auto-generated-prop-name-table:Props>\n public interface Props {\n String value = \"value\";\n }\n// </auto-generated-prop-name-table:Props>\n}",
                    "package sample; class Foo {\n int keep; public interface Props {\n String value = \"value\";\n }\n}",
                    "package sample; class Foo {\n int keep; /**\n * Auto-generated class for property(field) name table.\n */\n public interface Props {\n String value = \"value\";\n }\n}")) {
                Files.writeString(source, invalid);
                assertThrows(IllegalStateException.class, () -> CodeGenerationUtil.generatePropNameTableClass(entity, "Props", root.toString()));
                assertEquals(invalid, Files.readString(source));
            }
            final String bom = "\uFEFFpackage sample;\r\npublic class Foo { public String getValue() { return \"你好\"; } }\r\n";
            Files.writeString(source, bom);
            CodeGenerationUtil.generatePropNameTableClass(entity, "Props", root.toString());
            assertTrue(Files.readString(source).startsWith("\uFEFFpackage sample;\r\n"));
        }
    }

    private static void compile(Path source, Path output) {
        final ByteArrayOutputStream diagnostics = new ByteArrayOutputStream();
        assertEquals(0, ToolProvider.getSystemJavaCompiler().run(null, null, diagnostics, "-encoding", "UTF-8", "-proc:none", "-d", output.toString(), source.toString()),
                diagnostics.toString(StandardCharsets.UTF_8));
    }
}
