/*
 * Copyright (C) 2016 HaiYang Li
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.landawn.abacus.util.function;

import com.landawn.abacus.util.Throwables;

/**
 * Represents a supplier of {@code int}-valued results. This is the {@code int}-producing
 * primitive specialization of {@link java.util.function.Supplier}.
 *
 * <p>This interface extends both {@link java.util.function.IntSupplier} and
 * {@link Throwables.IntSupplier}, providing compatibility with the standard Java functional
 * interfaces while also supporting the Throwables framework.
 *
 * <p>There is no requirement that a distinct result be returned each time the supplier is invoked.
 *
 * <p>This is a functional interface whose functional method is {@link #getAsInt()}.
 *
 * <p>Refer to JDK API documentation at: <a href="https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/function/package-summary.html">https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/function/package-summary.html</a>
 *
 * @see java.util.function.Supplier
 */
@FunctionalInterface
public interface IntSupplier extends Throwables.IntSupplier<RuntimeException>, java.util.function.IntSupplier { //NOSONAR

    /**
     * A supplier that always returns zero.
     */
    IntSupplier ZERO = () -> 0;

    /**
     * A supplier that returns random {@code int} values. Each invocation returns a new random value
     * generated by the internal random number generator.
     */
    IntSupplier RANDOM = Util.RAND_INT::nextInt;

    /**
     * Gets a result.
     *
     * @return an {@code int} value
     */
    @Override
    int getAsInt();
}