/*
 * Generated by Abacus.
 */
package com.landawn.abacus.util.entity;

import java.sql.Timestamp;
import java.util.Objects;

import com.landawn.abacus.annotation.Type;

public class AccountContact implements ExtendDirtyBasicPNL.AccountContactPNL {
    private long id;
    private long accountId;
    private String mobile;
    private String telephone;
    private String email;
    private String address;
    private String address2;
    private String city;
    private String state;
    private String country;
    private String zipCode;
    private String category;
    private String description;
    private int status;
    private Timestamp lastUpdateTime;
    private Timestamp createdTime;

    public AccountContact() {
    }

    public AccountContact(long id) {
        this();

        setId(id);
    }

    public AccountContact(long accountId, String mobile, String telephone, String email, String address, String address2, String city, String state,
            String country, String zipCode, String category, String description, int status, Timestamp lastUpdateTime, Timestamp createdTime) {
        this();

        setAccountId(accountId);
        setMobile(mobile);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        setAddress2(address2);
        setCity(city);
        setState(state);
        setCountry(country);
        setZipCode(zipCode);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreatedTime(createdTime);
    }

    public AccountContact(long id, long accountId, String mobile, String telephone, String email, String address, String address2, String city, String state,
            String country, String zipCode, String category, String description, int status, Timestamp lastUpdateTime, Timestamp createdTime) {
        this();

        setId(id);
        setAccountId(accountId);
        setMobile(mobile);
        setTelephone(telephone);
        setEmail(email);
        setAddress(address);
        setAddress2(address2);
        setCity(city);
        setState(state);
        setCountry(country);
        setZipCode(zipCode);
        setCategory(category);
        setDescription(description);
        setStatus(status);
        setLastUpdateTime(lastUpdateTime);
        setCreatedTime(createdTime);
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public AccountContact setId(long id) {
        this.id = id;

        return this;
    }

    @Type("long")
    public long getAccountId() {
        return accountId;
    }

    public AccountContact setAccountId(long accountId) {
        this.accountId = accountId;

        return this;
    }

    @Type("String")
    public String getMobile() {
        return mobile;
    }

    public AccountContact setMobile(String mobile) {
        this.mobile = mobile;

        return this;
    }

    @Type("String")
    public String getTelephone() {
        return telephone;
    }

    public AccountContact setTelephone(String telephone) {
        this.telephone = telephone;

        return this;
    }

    @Type("String")
    public String getEmail() {
        return email;
    }

    public AccountContact setEmail(String email) {
        this.email = email;

        return this;
    }

    @Type("String")
    public String getAddress() {
        return address;
    }

    public AccountContact setAddress(String address) {
        this.address = address;

        return this;
    }

    @Type("String")
    public String getAddress2() {
        return address2;
    }

    public AccountContact setAddress2(String address2) {
        this.address2 = address2;

        return this;
    }

    @Type("String")
    public String getCity() {
        return city;
    }

    public AccountContact setCity(String city) {
        this.city = city;

        return this;
    }

    @Type("String")
    public String getState() {
        return state;
    }

    public AccountContact setState(String state) {
        this.state = state;

        return this;
    }

    @Type("String")
    public String getCountry() {
        return country;
    }

    public AccountContact setCountry(String country) {
        this.country = country;

        return this;
    }

    @Type("String")
    public String getZipCode() {
        return zipCode;
    }

    public AccountContact setZipCode(String zipCode) {
        this.zipCode = zipCode;

        return this;
    }

    @Type("String")
    public String getCategory() {
        return category;
    }

    public AccountContact setCategory(String category) {
        this.category = category;

        return this;
    }

    @Type("String")
    public String getDescription() {
        return description;
    }

    public AccountContact setDescription(String description) {
        this.description = description;

        return this;
    }

    @Type("int")
    public int getStatus() {
        return status;
    }

    public AccountContact setStatus(int status) {
        this.status = status;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getLastUpdateTime() {
        return lastUpdateTime;
    }

    public AccountContact setLastUpdateTime(Timestamp lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getCreatedTime() {
        return createdTime;
    }

    public AccountContact setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;

        return this;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(id);
        h = 31 * h + Objects.hashCode(accountId);
        h = 31 * h + Objects.hashCode(mobile);
        h = 31 * h + Objects.hashCode(telephone);
        h = 31 * h + Objects.hashCode(email);
        h = 31 * h + Objects.hashCode(address);
        h = 31 * h + Objects.hashCode(address2);
        h = 31 * h + Objects.hashCode(city);
        h = 31 * h + Objects.hashCode(state);
        h = 31 * h + Objects.hashCode(country);
        h = 31 * h + Objects.hashCode(zipCode);
        h = 31 * h + Objects.hashCode(category);
        h = 31 * h + Objects.hashCode(description);
        h = 31 * h + Objects.hashCode(status);
        h = 31 * h + Objects.hashCode(lastUpdateTime);
        return 31 * h + Objects.hashCode(createdTime);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof AccountContact other) {
            return Objects.equals(id, other.id) && Objects.equals(accountId, other.accountId) && Objects.equals(mobile, other.mobile)
                    && Objects.equals(telephone, other.telephone) && Objects.equals(email, other.email) && Objects.equals(address, other.address)
                    && Objects.equals(address2, other.address2) && Objects.equals(city, other.city) && Objects.equals(state, other.state)
                    && Objects.equals(country, other.country) && Objects.equals(zipCode, other.zipCode) && Objects.equals(category, other.category)
                    && Objects.equals(description, other.description) && Objects.equals(status, other.status)
                    && Objects.equals(lastUpdateTime, other.lastUpdateTime) && Objects.equals(createdTime, other.createdTime);
        }

        return false;
    }

    @Override
    public String toString() {
        return "{id=" + Objects.toString(id) + ", accountId=" + Objects.toString(accountId) + ", mobile=" + Objects.toString(mobile) + ", telephone="
                + Objects.toString(telephone) + ", email=" + Objects.toString(email) + ", address=" + Objects.toString(address) + ", address2="
                + Objects.toString(address2) + ", city=" + Objects.toString(city) + ", state=" + Objects.toString(state) + ", country="
                + Objects.toString(country) + ", zipCode=" + Objects.toString(zipCode) + ", category=" + Objects.toString(category) + ", description="
                + Objects.toString(description) + ", status=" + Objects.toString(status) + ", lastUpdateTime=" + Objects.toString(lastUpdateTime)
                + ", createdTime=" + Objects.toString(createdTime) + "}";
    }
}
