package com.landawn.abacus.util.entity;

import java.sql.Date;
import java.util.Map;

public class AutoGeneratedClass0 {

    private int field1;
    private Map<Integer, Date> field2;

    public int getField1() {
        return field1;
    }

    public void setField1(int field1) {
        this.field1 = field1;
    }

    public Map<Integer, Date> getField2() {
        return field2;
    }

    public void setField2(Map<Integer, Date> field2) {
        this.field2 = field2;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + _N.hashCode(field1);
        return 31 * h + _N.hashCode(field2);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof AutoGeneratedClass0 other) {
            return _N.equals(field1, other.field1) && _N.equals(field2, other.field2);
        }

        return false;
    }

    @Override
    public String toString() {
        return "{field1=" + _N.toString(field1) + ", field2=" + _N.toString(field2) + "}";
    }
}
